import React, { useState, useEffect } from 'react';
import {
    Table, Button, Modal, Form, Input, Select, Switch, message,
    Card, Spin, Space, Tag, Tooltip, Badge, Popconfirm, Alert
} from 'antd';
import {
    PlusOutlined, DeleteOutlined, EditOutlined, UserOutlined,
    MailOutlined, LockOutlined, SafetyCertificateOutlined,
    CheckCircleOutlined, StopOutlined, ExclamationCircleOutlined,
    KeyOutlined, CopyOutlined, ReloadOutlined
} from '@ant-design/icons';
import axios from 'axios';

const RoleTag = ({ role }) => {
    if (role === 'admin') return <Tag color="purple" icon={<SafetyCertificateOutlined />}>Admin</Tag>;
    return <Tag color="blue" icon={<UserOutlined />}>User</Tag>;
};

const StatusBadge = ({ active }) =>
    active
        ? <Badge status="success" text="Active" />
        : <Badge status="default" text="Inactive" />;

const UsersPage = () => {
    const [loading, setLoading] = useState(true);
    const [users, setUsers] = useState([]);
    const [addModal, setAddModal] = useState(false);
    const [editModal, setEditModal] = useState({ open: false, user: null });
    const [apiKeyModal, setApiKeyModal] = useState({ open: false, user: null, key: null, generating: false });
    const [saving, setSaving] = useState(false);
    const [addForm] = Form.useForm();
    const [editForm] = Form.useForm();

    useEffect(() => { fetchUsers(); }, []);

    const fetchUsers = async () => {
        try {
            const res = await axios.get('/api/v1/users/');
            setUsers(res.data || []);
        } catch {
            message.error('Failed to load users');
        } finally {
            setLoading(false);
        }
    };

    const handleAdd = async (values) => {
        setSaving(true);
        try {
            await axios.post('/api/v1/users/', values);
            message.success(`User "${values.username}" created`);
            setAddModal(false);
            addForm.resetFields();
            fetchUsers();
        } catch (err) {
            message.error(err.response?.data?.detail || 'Failed to create user');
        } finally {
            setSaving(false);
        }
    };

    const handleEdit = async (values) => {
        setSaving(true);
        try {
            await axios.patch(`/api/v1/users/${editModal.user.id}`, values);
            message.success('User updated');
            setEditModal({ open: false, user: null });
            fetchUsers();
        } catch (err) {
            message.error(err.response?.data?.detail || 'Failed to update user');
        } finally {
            setSaving(false);
        }
    };

    const handleDelete = async (userId, username) => {
        try {
            await axios.delete(`/api/v1/users/${userId}`);
            message.success(`User "${username}" deleted`);
            fetchUsers();
        } catch (err) {
            message.error(err.response?.data?.detail || 'Failed to delete user');
        }
    };

    const openEdit = (user) => {
        setEditModal({ open: true, user });
        editForm.setFieldsValue({
            full_name: user.full_name,
            email: user.email,
            username: user.username,
            role: user.role,
            is_active: user.is_active,
        });
    };

    const generateApiKey = async (user) => {
        setApiKeyModal({ open: true, user, key: null, generating: true });
        try {
            const res = await axios.post(`/api/v1/users/${user.id}/api-key`, { description: 'Generated by admin' });
            setApiKeyModal(p => ({ ...p, key: res.data.api_key, generating: false }));
        } catch (err) {
            message.error(err.response?.data?.detail || 'Failed to generate API key');
            setApiKeyModal(p => ({ ...p, generating: false }));
        }
    };

    const copyToClipboard = (text) => {
        navigator.clipboard.writeText(text).then(
            () => message.success('Copied to clipboard'),
            () => message.error('Copy failed')
        );
    };

    const columns = [
        {
            title: 'Username',
            dataIndex: 'username',
            key: 'username',
            render: (text) => (
                <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                    <div style={{
                        width: 32, height: 32, borderRadius: '50%',
                        background: 'linear-gradient(135deg, #4f46e5, #7c3aed)',
                        display: 'flex', alignItems: 'center', justifyContent: 'center',
                        color: '#fff', fontSize: 13, fontWeight: 700, flexShrink: 0
                    }}>
                        {text[0].toUpperCase()}
                    </div>
                    <span style={{ fontWeight: 600 }}>{text}</span>
                </div>
            )
        },
        { title: 'Email', dataIndex: 'email', key: 'email' },
        {
            title: 'Full Name',
            dataIndex: 'full_name',
            key: 'full_name',
            render: (v) => v || <span style={{ color: '#94a3b8' }}>—</span>
        },
        {
            title: 'Role',
            dataIndex: 'role',
            key: 'role',
            render: (role) => <RoleTag role={role} />
        },
        {
            title: 'Status',
            dataIndex: 'is_active',
            key: 'is_active',
            render: (v) => <StatusBadge active={v} />
        },
        {
            title: 'Actions',
            key: 'actions',
            width: 180,
            render: (_, record) => (
                <Space size="small">
                    <Tooltip title="Edit user">
                        <Button size="small" icon={<EditOutlined />} onClick={() => openEdit(record)} />
                    </Tooltip>
                    <Tooltip title="Generate API key">
                        <Button size="small" icon={<KeyOutlined />} onClick={() => generateApiKey(record)} />
                    </Tooltip>
                    <Popconfirm
                        title={`Delete "${record.username}"?`}
                        description="This action cannot be undone."
                        okText="Delete"
                        okType="danger"
                        cancelText="Cancel"
                        icon={<ExclamationCircleOutlined style={{ color: '#ef4444' }} />}
                        onConfirm={() => handleDelete(record.id, record.username)}
                    >
                        <Tooltip title="Delete user">
                            <Button size="small" danger icon={<DeleteOutlined />} />
                        </Tooltip>
                    </Popconfirm>
                </Space>
            )
        }
    ];

    if (loading) {
        return <div style={{ display: 'flex', justifyContent: 'center', padding: 60 }}><Spin size="large" /></div>;
    }

    return (
        <div className="content-wrapper">
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 24 }}>
                <div>
                    <h1 className="page-title">Users Management</h1>
                    <p className="page-subtitle">Manage system users, roles, and API access</p>
                </div>
                <Button type="primary" icon={<PlusOutlined />} size="large" onClick={() => setAddModal(true)}>
                    Add User
                </Button>
            </div>

            <Card>
                <Table
                    columns={columns}
                    dataSource={users}
                    rowKey="id"
                    pagination={{ pageSize: 10, showTotal: (t) => `${t} users` }}
                    locale={{ emptyText: 'No users found.' }}
                    size="middle"
                />
            </Card>

            {/* Add User Modal */}
            <Modal
                title={<span><PlusOutlined /> Add New User</span>}
                open={addModal}
                onCancel={() => { setAddModal(false); addForm.resetFields(); }}
                footer={null}
                width={520}
            >
                <Form form={addForm} layout="vertical" onFinish={handleAdd} style={{ marginTop: 16 }}>
                    <Form.Item
                        label="Username"
                        name="username"
                        rules={[
                            { required: true, message: 'Username is required' },
                            { min: 3, message: 'At least 3 characters' },
                            { pattern: /^[a-zA-Z0-9_.-]+$/, message: 'Only letters, numbers, _ . -' }
                        ]}
                    >
                        <Input prefix={<UserOutlined />} placeholder="john_doe" />
                    </Form.Item>
                    <Form.Item
                        label="Email"
                        name="email"
                        rules={[
                            { required: true, message: 'Email is required' },
                            { type: 'email', message: 'Invalid email address' }
                        ]}
                    >
                        <Input prefix={<MailOutlined />} placeholder="john@example.com" />
                    </Form.Item>
                    <Form.Item label="Full Name" name="full_name">
                        <Input prefix={<UserOutlined />} placeholder="John Doe" />
                    </Form.Item>
                    <Form.Item
                        label="Password"
                        name="password"
                        rules={[
                            { required: true, message: 'Password is required' },
                            { min: 8, message: 'At least 8 characters' }
                        ]}
                    >
                        <Input.Password prefix={<LockOutlined />} placeholder="Min. 8 characters" />
                    </Form.Item>
                    <Form.Item style={{ marginBottom: 0, textAlign: 'right' }}>
                        <Space>
                            <Button onClick={() => { setAddModal(false); addForm.resetFields(); }}>Cancel</Button>
                            <Button type="primary" htmlType="submit" loading={saving}>Create User</Button>
                        </Space>
                    </Form.Item>
                </Form>
            </Modal>

            {/* Edit User Modal */}
            <Modal
                title={<span><EditOutlined /> Edit User — <span style={{ color: '#4f46e5' }}>{editModal.user?.username}</span></span>}
                open={editModal.open}
                onCancel={() => setEditModal({ open: false, user: null })}
                footer={null}
                width={520}
            >
                <Form form={editForm} layout="vertical" onFinish={handleEdit} style={{ marginTop: 16 }}>
                    <Form.Item label="Full Name" name="full_name">
                        <Input prefix={<UserOutlined />} placeholder="Full name" />
                    </Form.Item>
                    <Form.Item
                        label="Email"
                        name="email"
                        rules={[{ type: 'email', message: 'Invalid email address' }]}
                    >
                        <Input prefix={<MailOutlined />} />
                    </Form.Item>
                    <Form.Item label="Username" name="username">
                        <Input prefix={<UserOutlined />} />
                    </Form.Item>
                    <Form.Item label="Role" name="role">
                        <Select>
                            <Select.Option value="user"><RoleTag role="user" /></Select.Option>
                            <Select.Option value="admin"><RoleTag role="admin" /></Select.Option>
                        </Select>
                    </Form.Item>
                    <Form.Item label="Active" name="is_active" valuePropName="checked">
                        <Switch checkedChildren={<CheckCircleOutlined />} unCheckedChildren={<StopOutlined />} />
                    </Form.Item>
                    <Form.Item style={{ marginBottom: 0, textAlign: 'right' }}>
                        <Space>
                            <Button onClick={() => setEditModal({ open: false, user: null })}>Cancel</Button>
                            <Button type="primary" htmlType="submit" loading={saving}>Save Changes</Button>
                        </Space>
                    </Form.Item>
                </Form>
            </Modal>

            {/* API Key Modal */}
            <Modal
                title={<span><KeyOutlined /> API Key — <span style={{ color: '#4f46e5' }}>{apiKeyModal.user?.username}</span></span>}
                open={apiKeyModal.open}
                onCancel={() => setApiKeyModal({ open: false, user: null, key: null, generating: false })}
                footer={[
                    <Button key="close" onClick={() => setApiKeyModal({ open: false, user: null, key: null, generating: false })}>
                        Close
                    </Button>,
                    !apiKeyModal.key && (
                        <Button key="gen" type="primary" icon={<ReloadOutlined />}
                            loading={apiKeyModal.generating}
                            onClick={() => generateApiKey(apiKeyModal.user)}>
                            Generate New Key
                        </Button>
                    )
                ]}
                width={560}
            >
                {apiKeyModal.generating && (
                    <div style={{ textAlign: 'center', padding: 24 }}><Spin /> Generating…</div>
                )}
                {apiKeyModal.key && (
                    <div>
                        <Alert
                            type="warning"
                            showIcon
                            message="Copy this key now — it will not be shown again."
                            style={{ marginBottom: 16 }}
                        />
                        <div style={{
                            background: '#0f172a', borderRadius: 8, padding: '12px 16px',
                            fontFamily: 'monospace', fontSize: 13, color: '#a5f3fc',
                            wordBreak: 'break-all', position: 'relative', paddingRight: 44
                        }}>
                            {apiKeyModal.key}
                            <Tooltip title="Copy">
                                <Button
                                    size="small" type="text" icon={<CopyOutlined />}
                                    onClick={() => copyToClipboard(apiKeyModal.key)}
                                    style={{
                                        position: 'absolute', top: 8, right: 8,
                                        color: '#7dd3fc', background: 'rgba(255,255,255,0.08)'
                                    }}
                                />
                            </Tooltip>
                        </div>
                    </div>
                )}
                {!apiKeyModal.generating && !apiKeyModal.key && (
                    <p style={{ color: '#64748b' }}>
                        Click "Generate New Key" to create or rotate the API key for this user.
                        The previous key will be immediately invalidated.
                    </p>
                )}
            </Modal>
        </div>
    );
};

export default UsersPage;
